spring:
  application:
    name: infotrucks
  # Configuração do banco de dados (padrão: H2 para dev)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:smarttruckdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driverClassName: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}
    locations: classpath:db/migration
  # Configuração de tamanho máximo para upload de arquivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /api

# Configurações dos bots
bot:
  telegram:
    username: ${TELEGRAM_BOT_USERNAME}
    token: ${TELEGRAM_BOT_TOKEN}
  whatsapp:
    verify-token: ${WHATSAPP_VERIFY_TOKEN}
    access-token: ${WHATSAPP_ACCESS_TOKEN}
    app-secret: ${WHATSAPP_APP_SECRET}

# Configurações de cache
cache:
  ttl: 3600 # Tempo de vida do cache em segundos
  max-size: 1000 # Número máximo de entradas no cache

# Configurações do sistema de tickets
ticket:
  sla: 14400 # Tempo de SLA em segundos (4 horas)
  auto-close: 172800 # Tempo para auto-fechamento em segundos (48 horas)

# Configurações de logging
logging:
  level:
    com.smarttruck: INFO
    org.springframework: WARN
